-- Table Insertation
--------------------------------------------------------------------------------------------------------------------------------
-- USUARIOS Table
----------------------------------------------------------
INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('Joseph', 'Joseph', 0);

INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('Ivan', 'Ivan', 0);

INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('Allan', 'Allan', 0);

INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('CCSS', 'admin', 0);

INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('AYA', 'admin', 0);

INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('ICE', 'admin', 0);

INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('CNFL', 'admin', 0);

INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('TIGO', 'admin', 0);

INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('KOLBI', 'admin', 0);

INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('INS', 'admin', 0);

INSERT INTO USUARIOS(USERNAME, PASSWORD, INTENTOS)
VALUES
('COSEVI', 'admin', 0);

-- DIVISAS Table
----------------------------------------------------------
INSERT INTO DIVISAS(NOMBRE, PRECIO_VENTA, PRECIO_COMPRA)
VALUES
('Colones', 0.0016, 0.0018);

INSERT INTO DIVISAS(NOMBRE, PRECIO_VENTA, PRECIO_COMPRA)
VALUES
('Dolar', 1, 1.2);

INSERT INTO DIVISAS(NOMBRE, PRECIO_VENTA, PRECIO_COMPRA)
VALUES
('Euro', 1.13, 1.25);

-- MOVIMIENTOS_DISPONIBLES Table
----------------------------------------------------------
INSERT INTO MOVIMIENTOS_DISPONIBLES(SINPE_MOVIL, SINPE)
VALUES
(1, 1);

INSERT INTO MOVIMIENTOS_DISPONIBLES(SINPE_MOVIL, SINPE)
VALUES
(0, 1);

INSERT INTO MOVIMIENTOS_DISPONIBLES(SINPE_MOVIL, SINPE)
VALUES
(0, 0);

-- CUENTAS Table
----------------------------------------------------------
INSERT INTO CUENTAS(ID_USER, ID_DIVISA, ID_MOVIMIENTO, IBAN, SALDO_TOTAL, SALDO_ACTUAL, SALDO_RETENIDO, CREDITO)
VALUES
(1, 1, 1, 'CR123456891010', 150000, 85000, 65000, 0);

INSERT INTO CUENTAS(ID_USER, ID_DIVISA, ID_MOVIMIENTO,  IBAN, SALDO_TOTAL, SALDO_ACTUAL, SALDO_RETENIDO, CREDITO)
VALUES
(2, 2, 2, 'CR12388999201', 800000, 5000, 75000, 0);

INSERT INTO CUENTAS(ID_USER, ID_DIVISA, ID_MOVIMIENTO,  IBAN, SALDO_TOTAL, SALDO_ACTUAL, SALDO_RETENIDO, CREDITO)
VALUES
(3, 3, 3, 'CR123453445010', 10000000, 0, 65000, 1);

-- TIPO_CEDULAS Table
----------------------------------------------------------
INSERT INTO TIPOS_CEDULAS(DESCRIPCION, PAIS_ORIGEN)
VALUES
('Costarricense', 'Costa Rica');

INSERT INTO TIPOS_CEDULAS(DESCRIPCION, PAIS_ORIGEN)
VALUES
('Estadounidense', 'La United');

INSERT INTO TIPOS_CEDULAS(DESCRIPCION, PAIS_ORIGEN)
VALUES
('Europeo', 'Europa XD');

-- USUARIOS_INFO Table
----------------------------------------------------------
INSERT INTO USUARIOS_INFO(ID_USER, ID_CEDULA, NOMBRE, APELLIDO, CEDULA, TELEFONO, CORREO, DIRECCION)
VALUES
(1, 1, 'Joseph', 'Mesen', '118180569', '87281936', 'joemesoto@gmail.com', 'Mikasa XD');

INSERT INTO USUARIOS_INFO(ID_USER, ID_CEDULA, NOMBRE, APELLIDO, CEDULA, TELEFONO, CORREO, DIRECCION)
VALUES
(2, 2, 'Ivan', 'Pichanana', '118180568', '87281935', 'joemesoto@hotmail.com', 'En la avispa');

INSERT INTO USUARIOS_INFO(ID_USER, ID_CEDULA, NOMBRE, APELLIDO, CEDULA, TELEFONO, CORREO, DIRECCION)
VALUES
(2, 2, 'Allan', 'Pichorta', '118180567', '87281934', 'joemesoto@outlook.com', 'En la pinga Joseph');

-- EMPRESAS Table
----------------------------------------------------------
INSERT INTO EMPRESAS(ID_USER, NOMBRE, DESCRIPCION)
VALUES
(4, 'CCSS', 'Servicio de salud');

INSERT INTO EMPRESAS(ID_USER, NOMBRE, DESCRIPCION)
VALUES
(5, 'AYA', 'Servicio de agua');

INSERT INTO EMPRESAS(ID_USER, NOMBRE, DESCRIPCION)
VALUES
(6, 'ICE', 'Servicio de electricidad');

INSERT INTO EMPRESAS(ID_USER, NOMBRE, DESCRIPCION)
VALUES
(7, 'CCSS', 'Servicio de electricidad');

INSERT INTO EMPRESAS(ID_USER, NOMBRE, DESCRIPCION)
VALUES
(8, 'TIGO', 'Servicio de telecomunicaciones');

INSERT INTO EMPRESAS(ID_USER, NOMBRE, DESCRIPCION)
VALUES
(9, 'KOLBI', 'Servicio de telecomunicaciones');

INSERT INTO EMPRESAS(ID_USER, NOMBRE, DESCRIPCION)
VALUES
(10, 'INS', 'Servicio de seguros');

INSERT INTO EMPRESAS(ID_USER, NOMBRE, DESCRIPCION)
VALUES
(11, 'COSEVI', 'Servicio de transporte');

-- ESTADOS Table
----------------------------------------------------------
INSERT INTO ESTADOS(ID_STATUS, DESCRIPCION)
VALUES
(200, 'Exitoso');

INSERT INTO ESTADOS(ID_STATUS, DESCRIPCION)
VALUES
(300, 'Pendiente');

INSERT INTO ESTADOS(ID_STATUS, DESCRIPCION)
VALUES
(500, 'Error');

-- HISTORIAL_TRANSACCIONES Table
----------------------------------------------------------
INSERT INTO HISTORIAL_TRANSACCIONES(ID_USER, ID_CUENTA_ORIGEN, ID_CUENTA_DESTINO, ID_STATUS, MONTO, DESCRIPCION)
VALUES
(1, 1, 2, 300, 1000, 'Test 1');

INSERT INTO HISTORIAL_TRANSACCIONES(ID_USER, ID_CUENTA_ORIGEN, ID_CUENTA_DESTINO, ID_STATUS, MONTO, DESCRIPCION)
VALUES
(2, 2, 2, 200, 2000, 'Test 2');

INSERT INTO HISTORIAL_TRANSACCIONES(ID_USER, ID_CUENTA_ORIGEN, ID_CUENTA_DESTINO, ID_STATUS, MONTO, DESCRIPCION)
VALUES
(3, 3, 1, 300, 1000, 'Test 3');

-- SERVICIOS Table
----------------------------------------------------------
INSERT INTO SERVICIOS(ID_EMPRESA, DESCRIPCION)
VALUES
(1, 'Servicio de salud');

INSERT INTO SERVICIOS(ID_EMPRESA, DESCRIPCION)
VALUES
(2, 'Servicio de agua');

INSERT INTO SERVICIOS(ID_EMPRESA, DESCRIPCION)
VALUES
(3, 'Servicio de electricidad');

<<<<<<< Updated upstream
-- Insertar tipo de cedula

INSERT INTO TIPOCEDULA(IDTIPOCEDULA, DESCRIPCION)
VALUES(3, 'NACIONAL');

INSERT INTO TIPOCEDULA(IDTIPOCEDULA, DESCRIPCION)
VALUES(2, 'EXTRANJERO');

INSERT INTO TIPOCEDULA(IDTIPOCEDULA, DESCRIPCION)
VALUES(1, 'DIMEX');

-- Insertar personal info
INSERT INTO USUARIO_PERSONAL_INFO(IDPERSONALINFO, IDUSER, IDTIPOCEDULA, NOMBRE, APELLIDO, CEDULA, TELEFONO, CORREO, DIRECCION)
VALUES (1, 1, 1, 'admin', 'admin', 12345678, 89988818, 'admin@gmail.com', 'Pavas')
=======
INSERT INTO SERVICIOS(ID_EMPRESA, DESCRIPCION)
VALUES
(4, 'Servicio de electricidad');

INSERT INTO SERVICIOS(ID_EMPRESA, DESCRIPCION)
VALUES
(5, 'Servicio de telecomunicaciones');

INSERT INTO SERVICIOS(ID_EMPRESA, DESCRIPCION)
VALUES
(6, 'Servicio de telecomunicaciones');

INSERT INTO SERVICIOS(ID_EMPRESA, DESCRIPCION)
VALUES
(7, 'Servicio de seguros');

INSERT INTO SERVICIOS(ID_EMPRESA, DESCRIPCION)
VALUES
(8, 'Servicio de transporte');

-- FACTURAS Table
----------------------------------------------------------
INSERT INTO FACTURAS(ID_TRANSACCION, ID_SERVICIO, ID_STATUS)
VALUES
(1, 1, 200);

INSERT INTO FACTURAS(ID_TRANSACCION, ID_SERVICIO, ID_STATUS)
VALUES
(1, 1, 200);

INSERT INTO FACTURAS(ID_TRANSACCION, ID_SERVICIO, ID_STATUS)
VALUES
(1, 1, 200);
>>>>>>> Stashed changes
